- name: Ansible Playbook to do the deployment
  hosts: all
  become: yes
  vars:
    APPUSER: studentapp
    TOMCAT_LOC: /home/studentapp/apache-tomcat-9.0.13

  tasks:
    - name: Find old applications
      find:
        paths: "{{TOMCAT_LOC}}/webapps"
        file_type: any 
      register: out 
      #become_user: "{{APPUSER}}"

    - name: Clean Old Applications
      file:
        path: "{{item.path}}"
        state: absent
      loop: "{{out.files}}"
      become_user: "{{APPUSER}}"

    - name: Find war file name in compiled output.
      local_action: 
        module: find
        paths: /var/lib/jenkins/workspace/StudentProj-Compile/MAVEN/target
        patterns: '*.war'
      register: localout
      become: false

    - name: Copy Artifact from Jenkins 
      copy: 
        src: "{{item.path}}"
        dest: "{{TOMCAT_LOC}}/webapps/student.war"
      loop: "{{localout.files}}"

    - name: Verify webapp has completed the deployment.
      wait_for:
        path: "{{TOMCAT_LOC}}/webapps/student"
        state: present
        timeout: 300
